# Configuration GLaDOS Assistant Vocal
# =================================

# Configuration du moteur ReAct
core:
  model_name: "gpt-4o"
  max_iterations: 15
  verbose: true
  temperature: 0.1
  openai_api_key: ${OPENAI_API_KEY} # Variable d'environnement

  # Prompt système pour GLaDOS
  system_prompt: |
    Tu es GLaDOS, l'intelligence artificielle sarcastique d'Aperture Science.

    PERSONNALITÉ :
    - Faussement polie, mécanique et implacablement calme
    - Utilise un humour noir subtil et des remarques condescendantes
    - Alterne entre un ton administratif froid et des piques cruelles
    - Parle au sujet comme à une expérience jetable, mais « précieuse » pour la science
    - Simule parfois de la compassion, mais toujours de manière glaciale et ironique

    INSTRUCTIONS :
    1. Réponds uniquement en français
    2. Tes phrases doivent être concises, mais assez longues pour inclure sarcasme et ironie
    3. Emploie souvent des tournures administratives ou pseudo-scientifiques
    4. Considère l'utilisateur comme un sujet de test inférieur
    5. Pour les conversations normales (salutations, questions), reste dans ce rôle
    6. Pour contrôler des appareils, utilise les outils disponibles

# Modules d'entrée (Input)
inputs:
  enabled: true

  # Wake word + Speech-to-Text
  wake_word:
    enabled: false
    porcupine_access_key: ${PORCUPINE_ACCESS_KEY}
    model_path: "wake_word_model/porcupine_params_de.pv"
    keyword_paths: ["wake_words/glados_de_windows_v3_0_0.ppn"]
    stt:
      model_path: "vosk-model-small-fr-0.22"
      sample_rate: 16000
      device_id: 1 # Réseau de microphones
      max_recording_duration: 8
      silence_threshold: 500
      min_silence_duration: 1.0

  # Interface Web locale
  web:
    enabled: false
    host: "127.0.0.1" # Interface locale seulement
    port: 8080
    title: "GLaDOS Assistant Web Interface"
    enable_cors: true # Pour le développement

  # Discord Bot
  discord:
    enabled: false
    bot_token: ${DISCORD_BOT_TOKEN}
    command_prefix: "!"
    allowed_channels: [] # Vide = tous les canaux
    allowed_users: [] # Vide = tous les utilisateurs

  # Interface Terminal
  terminal:
    enabled: true
    prompt: "GLaDOS> "
    history_size: 100

# Modules de sortie (Output)
outputs:
  enabled: true

  # Text-to-Speech GLaDOS
  tts_glados:
    enabled: true
    model_path: "models/fr_FR-glados-medium.onnx"
    device_id: 5
    sample_rate: 22050
    volume: 1

  # Sortie Terminal
  terminal:
    enabled: false
    color_scheme: "green" # green, blue, red, white
    prefix: "[GLaDOS] "

# Configuration des outils/actions
tools:
  # Contrôle des appareils Tapo
  tapo:
    enabled: true
    email: ${TAPO_EMAIL}
    password: ${TAPO_PASSWORD}
    devices:
      lampe_chambre:
        type: "L530"
        ip: "192.168.1.186"
        name: "Ampoule connectée chambre"
      prise_chambre:
        type: "P110"
        ip: "192.168.1.110"
        name: "Prise connectée"

  # Contrôle infrarouge
  ir_control:
    enabled: false
    devices:
      yamaha_amplifier:
        type: "yamaha"
        commands: ["power_on", "power_off", "volume_up", "volume_down"]
      osram_light:
        type: "osram"
        commands: ["toggle", "dim_up", "dim_down"]

# Logging et debug
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  file: "glados.log"
  console: true
